"""create workspaces table

Revision ID: ebbae282a8cc
Revises: 300bf1a46e3c
Create Date: 2025-08-07 15:05:51.662969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebbae282a8cc"
down_revision: Union[str, Sequence[str], None] = "300bf1a46e3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("workspaces_pkey")),
        sa.UniqueConstraint("name", name=op.f("workspaces_name_key")),
    )
    op.create_foreign_key(
        op.f("chat_sessions_workspace_id_workspaces_fkey"),
        "chat_sessions",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("chat_sessions_workspace_id_workspaces_fkey"), "chat_sessions", type_="foreignkey")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
