"""create chat_message_sources table

Revision ID: f2b9e2e48467
Revises: ebbae282a8cc
Create Date: 2025-08-20 18:18:34.291592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2b9e2e48467"
down_revision: Union[str, Sequence[str], None] = "ebbae282a8cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_message_sources",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("message_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("document_name", sa.String(), nullable=False),
        sa.Column("document_page", sa.BigInteger(), nullable=False),
        sa.Column("snippet", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["chat_messages.id"],
            name=op.f("chat_message_sources_message_id_chat_messages_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_message_sources_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_message_sources")
    # ### end Alembic commands ###
